Data Manipulation:

      data manipulation in python refers to the process of changing or oragnising the data to make it easier to work with , analyze or visualize.

      Thia data cleaning usually involves transformation ,filtering,cleaning the data so that its in right format or structure of yourb specific needs.

      libraries used for data manipulation is numpy and pandas.
       

**Numpy**:

   
   it is a mathematical lybrary that is used for mathmatical operations. we will used in arrays , list ,sets etc.

 **Pandas**:


   pandas is used tom perform data cleaning.

 **Matplotlib / Seaborn**:


      both are used for visualization where matplotlib only do
      basic styling using manual approach but seaborn
      have built in styling methods which applied automatically.    

**Numpy**- is a powerful lybrary used for numerical operation.

it provide a large amount of support to handle multidimention arrays.

it is a collection of high level mathematical functions to operate on these arrays.

numpy is used when u need to handle large data set of numbers or perform mathematical operations on them.

it is widely used in data science,machine learning and scientfic computing.

numpy includes many built in function like addition ,subctraction, square root,trignometric matrix,vector etc which can be applied to whole data at once.

numpy is highely optimized and can perform operations on the large datasets much faster than standard python list.


why is this useful?
 1. speed
 2. less memory
 3. efficient
 4. simplicity

 application of numpy
 1. data analysis
 2. machine learning
 3. maths and statistics
 4. scientific computing
 5. image processing






In [ ]:
a =[1,2,3,4,5,6] #it is time taking or memory taking
sum =0
for i in a:
  sum+=i
print(sum)

21


In [ ]:
# what is numpy array

#it is a  used to store the collection of homogeneous data.(same datatyped values)

# it can  works with multidimentional array 1d,2d,3d to ndimential array.

#how to create a numpy array
# there are three deffrent ways to creatw a numpy arrays

#1 creating a numpy array from python list

import numpy as np
lst1 = [1,2,3,4,5,6]
arr =np.array(lst1)
type(arr)
arr


array([1, 2, 3, 4, 5, 6])

In [ ]:
# 2 create a numpy array with a range of values

# for loop ->range
#np.arange()

arr = np.arange(0,100,4)
arr

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [ ]:
# 3 create a numpy array filled with zeros
arr_zeros =np.zeros(50)
arr_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# create a numpy array with a specific shape filled
# with 2 dimensional data

# random
#2d data

arr_random = np.random.randint(1,5,size =(2,3))
print(arr_random)

#random.random - generate random value - float data
#random.rand -create a10 float random between o to 1

arr_rand = np.random.rand(5,5,5)
print(arr_rand)

arr_random = np.random.random(2)
print(arr_random)


[[3 1 2]
 [1 2 1]]
[[[0.05131704 0.92762259 0.03144944 0.80195442 0.71685561]
  [0.14241254 0.89753295 0.18996378 0.56983464 0.80926332]
  [0.79371741 0.0701811  0.11761287 0.53070887 0.77530022]
  [0.89948785 0.78287371 0.67072157 0.95196784 0.88310013]
  [0.78387989 0.76516305 0.61426288 0.18228703 0.27489189]]

 [[0.82747344 0.6502126  0.71734187 0.30841951 0.34208973]
  [0.85083965 0.91006105 0.49408113 0.03404054 0.70737925]
  [0.36438872 0.802207   0.50029969 0.07729776 0.54557017]
  [0.36726875 0.44411886 0.24937228 0.35344891 0.6602677 ]
  [0.71995182 0.50160152 0.03948855 0.91881943 0.95045311]]

 [[0.45549687 0.5989531  0.50351377 0.0584792  0.51659856]
  [0.12131543 0.63945609 0.12647906 0.58130313 0.40556562]
  [0.61667379 0.23873447 0.60948046 0.55810612 0.13895784]
  [0.83049466 0.3765124  0.36594063 0.16900011 0.32627722]
  [0.63282251 0.47578599 0.55512647 0.70208828 0.40551742]]

 [[0.15796936 0.84420132 0.38909549 0.11717646 0.73560076]
  [0.45182208 0.33321981 0.1483

In [ ]:
# 1 dimensional array
# 1d is simple list of values

arr_1d =np.array([1,2,3,4,5,6,7])

arr_1d.ndim       #  check the dimensione of 1d array
arr_1d.shape #shape of array

(7,)

In [ ]:
# 2 dimensional array
# 2d array is like a matrix with rows and column.
# think like a table

arr_2d=np.array([
    [1,2,3],
    [4,5,6]
])
arr_2d.ndim #check the dimensiobn of 2d array
arr_2d.shape #shape of array (2,3)-->(rows,column)

(2, 3)

In [ ]:
# 3d array
# a 3d array is like a stack of 2d arrays
#collection of multiple 2d array stacked together


arr_3d = np.array([[[1,2,3],
                   [4,5,6]],

                   [[7,8,9],
                    [12,23,45]],

                   [[34,45,32],
                    [31,65,43]]])


arr_3d.ndim            #check the dimension of 3d array
arr_3d.shape #shape of the array (3,2,3)--->(no of 2d arrays,rows,column)

(3, 2, 3)

In [ ]:
#4d array
arr_4d=np.array([[[[1,2,3],
                   [2,3,4],
                   [3,4,5]],

                  [[1,2,3],
                   [2,3,4],
                   [3,4,5]],

                  [[1,2,3],
                   [2,3,4],
                   [3,4,5]]]])
arr_4d.ndim # check the dimension of 4d array
arr_4d.shape # shape of the 4d array (1,3,3,3)---->(Blocks, Matrices, Rows, Columns)


(1, 3, 3, 3)

In [ ]:
arr_5d=np.array([[[[[1,2,3],
                    [2,3,4],
                    [3,4,5]],

                    [[1,2,3],
                    [2,3,4],
                    [3,4,5]],

                    [[1,2,3],
                    [2,3,4],
                    [3,4,5]],

                    [[1,2,3],
                    [2,3,4],
                    [3,4,5]]]]])

arr_5d.ndim
arr_5d.shape

(1, 1, 4, 3, 3)

In [ ]:
arr =np.array([[[[[[1,2,3,4,5,6]]]]]])
arr.ndim
arr.shape

(1, 1, 1, 1, 1, 6)

In [ ]:
#data manipulation

# maths -numpy , data cleaning-pandas,plots or graphs -seaborn or matplotlib

#numpy array

#how to create a multidimentional array


In [ ]:
# array inspection

# 1. shape

# get the dimensions of an array
import numpy as np

arr = np.array([[[[1,2,3,4],[5,6,7,8]]]])

print(arr.ndim)
print(arr)
print(arr.shape)



# 1.1 2d array, 2 row, 4 element

# 1 3d array, 1 2d array, 2 row ,4 column(element)


4
[[[[1 2 3 4]
   [5 6 7 8]]]]
(1, 1, 2, 4)


In [ ]:
# size : get the total size of the array or total no. of element in array

print("size of the array is ",arr.size)

size of the array is  8


In [ ]:
# dtype : get the datatype of the elements in the array

arr1 = np.array([1,2,3,4,5,6.0,7])
print("datatype ",arr1.dtype)

datatype  float64


**ARRAY MANIPULATION METHOD**


In [ ]:
# 1. arange :

# create an array using start and stop pos

arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [ ]:
# 2. reshape :change the shape of the array without modifing the data

arr = np.arange(1,7)
print(arr)

# 2d : 2 rows and 3 colom

#2d : how many row and colom

#2,3 product should be = 12

reshape_data = arr.reshape(2,3)
print(reshape_data.ndim)
print(reshape_data)

[1 2 3 4 5 6]
2
[[1 2 3]
 [4 5 6]]


In [ ]:
a = np.arange(0,12)
a1 = a.reshape(4,3)
print(a1)
print(a1.ndim)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
2


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr.size)

#3d  row colum product = 9

arr = arr.reshape(1,3,3)
print(arr)
print(arr.ndim)

# 2d , rows , columns

9
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [ ]:
arra = np.array([[1,2,3],[4,5,6]])
print(arra.ndim)
arra

#2d to 3d

a = arra.reshape(1,2,3)
print(a)

2
[[[1 2 3]
  [4 5 6]]]


In [ ]:
arr3d = np.array([[1,2],[3,4],[5,6],[7,8]])
arr3d.size

a = arr3d.reshape(1,2,4)
print(a.ndim)
print(a)




#reshaping your data
# from 1d to 2d (no of rows ,no of columns)
# from 2d to 3d (no of 2d data ,no of rows , no of columns)
# from 3d to 4d (no of 3d ,no of 2d , no of rows ,no of columns)

3
[[[1 2 3 4]
  [5 6 7 8]]]


In [ ]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)

#3d  1 ,3,3

a = arr1.reshape(1,3,3)
print("array :",a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array : [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
# ravel :

# flatten your multi dimensinal array into 1d array

arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)

flatten = arr1.ravel()
print(flatten)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [ ]:
# 3d to 2d

arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3d.size)

arr2d = arr3d.reshape(3,3)
print(arr2d)

9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr3 = np.array([[[[1,2,3],[4,5,6]]]])
print(arr3)
#4d to 3d

arr3d = arr3.reshape(1,2,3)
print(arr3d)

[[[[1 2 3]
   [4 5 6]]]]
[[[1 2 3]
  [4 5 6]]]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("**")
transported_arr = arr.T
print(transported_arr)

[[1 2 3]
 [4 5 6]]
**
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#np.identity
import numpy as np


identity_matrix=np.identity(2)
print(identity_matrix)

#when u performing ml or linear alzebra operations
# multiplication on matrix with identity matrix
#the resultant values would be same
#used in solve linear equation
#regulization

[[1. 0.]
 [0. 1.]]


In [ ]:
#5
ide = np.identity(5)
print(ide)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# create a identity matrix of 2 and 5
i = np.identity(2)
i # we can only create a identity matrices for square matrix



array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [ ]:
#3 and 5

# np.eye


ip = np.eye(5,5,k=0)
ip

#it return your rectangular matrix

#one will on the diagonal and zeros elsewhere

#k : index of the diagonal


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(3,3).reshape(1,3,3) #2d identity to 3d identity

array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]])

In [ ]:
np.eye(1)

array([[1.]])

In [ ]:
np.eye(2,3).reshape(1,2,3)

array([[[1., 0., 0.],
        [0., 1., 0.]]])

In [ ]:
# where fun

#it is used  check the condition on the array

#np.where(condition  , value_if true ,value_if false)



In [ ]:
arr = np.array([5,-2,4,-6,8,9])

result = np.where(arr<0,0,arr)

#replace these negative to zero
result

array([5, 0, 4, 0, 8, 9])

In [ ]:
marks = np.array([56,36,45,23,80])

result = np.where(marks>=33 ,"pass","fail")
print(result)

['pass' 'pass' 'pass' 'fail' 'pass']


In [ ]:
sales = np.array([10,0,5,0,20])

#find the index of sales =0

sal_result =np.where(sales==0)
print(sal_result)
print("values ",sales[sal_result])

(array([1, 3]),)
values  [0 0]


In [ ]:
marks = np.array([56,36,45,23,80])
# count the no which is greater than 50

count = np.sum(marks>50)
print(count)

2


In [ ]:
# create an array of number 5 to 20
arr = np.arange(5,21)
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
# convert 1d to 2d ,3d
arr = np.arange(5,21)
print(arr.size)

print("2d")

a = arr.reshape(4,4)
print(a)

print("3d")

a = arr.reshape(1,4,4)
print(a)

16
2d
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
3d
[[[ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]
  [17 18 19 20]]]


In [ ]:
# flateen 2d ,3d to 1d
flaten = a.ravel()
print(flaten)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#flatten : - a copy of the array
arr = np.array([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


In [ ]:
f = arr.flatten()
f

array([1, 2, 3, 4])

In [ ]:
f[0] =10
print(f)
arr # it can not change the array and original data

[10  2  3  4]


array([[1, 2],
       [3, 4]])

In [ ]:
# ravel
arr1 = np.array([[1,2],[3,4]])
print(arr1)

# it can change the array and original data

r = arr1.ravel()
print(r)

r[1]=10
print(r)
arr1

[[1 2]
 [3 4]]
[1 2 3 4]
[ 1 10  3  4]


array([[ 1, 10],
       [ 3,  4]])

In [ ]:
a = np.array([1,2,3])
b =np.array([4,5,6])

# add two arrays

sum = a+b
print(sum)

add = np.add(a,b)
add


[5 7 9]


array([5, 7, 9])

In [ ]:
# subtract two arrays
a = np.array([1,2,3])
b =np.array([4,5,6])

c = a-b
c
sub = np.subtract(a,b)
print(sub)

[-3 -3 -3]


In [ ]:
# multiply
a = np.array([1,2,3])
b =np.array([4,5,6])

print(a*b)

print(np.multiply(a,b))

[ 4 10 18]
[ 4 10 18]


In [ ]:
a = np.array([1,2,3])
b =np.array([4,5,6])

# 1*4+2*5+3*6
#matmul

print(np.matmul(a,b))

32


In [ ]:
arr = np.array([10,15,20,25,40])

#return only even values

even = arr[arr%2 == 0]
even

array([10, 20, 40])

In [ ]:
# create a 3*3 identity matrix and convert to 4d matrix

id= np.identity(3)
id

id.reshape(1,1,3,3)

# 1 1:3d,1 1:2d,3 rows ,3 columns

array([[[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]]])

In [ ]:
arr =np.array([[10,20,30,40,50],[100,30,40,500,200]])

max = arr.max()
max

np.int64(500)

In [ ]:
scores = np.array([[94,89,88],
                  [10,30,80],
                  [78,98,67],
                  [45,65,99]])

#find all rows where column 0>80

scores1 = scores[: ,0]
result =scores1[scores1>80]
print(result)
print(scores1)

[94]
[94 10 78 45]


In [ ]:
# q1
array_float = np.array([[1,2,3],[3,4,5]],dtype='float')
print(array_float)

array_int =np.array([[2,3,4],[5,6,7]],dtype='int')
print(array_int)

[[1. 2. 3.]
 [3. 4. 5.]]
[[2 3 4]
 [5 6 7]]


**quetion 2**

In [ ]:
arr_zero =np.array(1) #no brackets zero d array
print(arr_zero.ndim)
print(arr_zero.size)



0
1


In [ ]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d.ndim)
print(arr_1d.size)

1
5


In [ ]:
arr_2d =np.array([[1,2,3],[4,5,6]])
print(arr_2d.ndim)
print(arr_2d.size)

2
6


In [ ]:
arr_3d =np.array([[[1,2,3],[4,5,6]]])
print(arr_3d.ndim)
print(arr_3d.size)

3
6


In [ ]:
arr_4d = np.array([[[[1,2,3],[4,5,6]]]])
print(arr_4d.ndim)
print(arr_4d.size)

4
6


**quetion 3**

In [ ]:
arrid =np.eye(2,3)
print(arrid)

[[1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
arr3id =np.identity(3)
print(arr3id)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr4id =np.identity(4)
arr4id

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**quetion 4**

In [ ]:
arr = np.zeros(10).reshape(2,5)
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr = np.zeros((2,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**quetion 5**

In [ ]:
arr = np.full((3,5),5)
arr

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

**quetion 6**

In [ ]:
arr_random = np.random.randint(0,101,25)
print(arr_random)

[ 68 100  39  43  41   8  34  74  77  40  33  24  85  22  96  26  92  97
  79  15  37  11  33  70  68]


**quetion 7**

In [ ]:
arr = np.full((3,3),1)
arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
arr = np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**quetion 8**

In [ ]:
arr_random = np.random.randint(0,101,size =(2,3))
print(arr_random)

reshape = arr_random.reshape(3,2)
reshape

[[ 80 100  60]
 [ 17  38  49]]


array([[ 80, 100],
       [ 60,  17],
       [ 38,  49]])

**quetion 9**

In [ ]:
arr_random = np.random.randint(0,1000,50)
print(arr_random)

for i in  range(10):   #arr_random[0:11]
  print(arr_random[i])



[744 182 320 918 361 846 110 331 429 188 666  20 966 148 600 277 939 874
 236 788 689 607 368 275 110 542 924 637 861 731 772 407 896 681 263  53
 297 780  41 328 775 450 223 174  31  97 820 510 411 227]
744
182
320
918
361
846
110
331
429
188


In [ ]:


for i in range(40,50):  #arr_random[40: ]
  print(arr_random[i])

775
450
223
174
31
97
820
510
411
227


In [ ]:
for i in range(10,25):  #arr_random[10:25]
  print(arr_random[i])

666
20
966
148
600
277
939
874
236
788
689
607
368
275
110


In [ ]:
print("at 22 index",arr_random[22])

at 22 index 368


In [ ]:
print(arr_random[-50:])

[744 182 320 918 361 846 110 331 429 188 666  20 966 148 600 277 939 874
 236 788 689 607 368 275 110 542 924 637 861 731 772 407 896 681 263  53
 297 780  41 328 775 450 223 174  31  97 820 510 411 227]


In [ ]:
print(arr_random[-10:])

[775 450 223 174  31  97 820 510 411 227]


**quetion 10**

In [ ]:
arr = np.array([1,2,3,4,5])
arr

new_arr = np.append(arr,6) #np.append(old_arr,value to add at last index or arr)
print(new_arr)

new_arr2 = np.insert(new_arr,0,10) # np.insert(old_arr,index,value to add with specific pos)
print(new_arr2)

new_arr3 = np.insert(new_arr2,4,30) # insert 30 before 4
print(new_arr3)

new_arr3[6] = 50 #update 5 as 50
print(new_arr3)

new_arr4 = np.delete(new_arr3,6) #delete 50 in the array
print(new_arr4)



[1 2 3 4 5 6]
[10  1  2  3  4  5  6]
[10  1  2  3 30  4  5  6]
[10  1  2  3 30  4 50  6]
[10  1  2  3 30  4  6]


In [ ]:
def search_element(array,element):
  return np.where(array==element)

result = search_element(arr,30)
result

(array([], dtype=int64),)

In [ ]:
arr = np.sort(arr)
arr

array([1, 2, 3, 4, 5])

In [ ]:
# numpy interview

# 1. what is numpy? why is it used
# 2. what is nd array?
# 3. why is numpy faster than list?
# 4. what are adv and limit of numpy
# 5. how do u create a numpy array
# 6. what is difference between zeros ,onces ,empty
# 7. what is dtype in np
# 8. what is shape , size ,ndim
# 9. how do u change dtype of an array
# 10. what is slicing
# 11. how do u access the item in array
# 12. what is difference between reshape and resize
# 13. diff b/w ravel and flatten
# 14. id to nd arr
# 15. transpose
# 16. statistics - mean median mode


In [ ]:
# create a array with number from 1 to 10 and and negate the element from index 3 to 5


In [ ]:
# create a 3d array using the values such that array has 3 dimensions using ndim
# after creating the array
#print the array and shape
